name: EPICS Base Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build EPICS Base
        run: |
          ls
          python scripts/base/install_requirements.sh
