name: EPICS Base Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@3
    
      - name: Build EPICS Base
        run: |
          ls
          bash scripts/base/install_requirements.sh
